spring:
  datasource:
    url: jdbc:mysql://47.105.143.40:3306/testdb?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.boot.demo.bootdemo.domain
  mapper-locations: classpath:mapper/*.xml

mapper:
  not-empty: false
  identity: MYSQL

server:
  port: 8081